### ISSUE TITLE
NPE when push cancel POS Dialog Selection  

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#28]
12:26:50.679 MChangeLog.fillChangeLog: #62 [31]
===========> AMenuStartItem.run: ID=419 [31]
java.lang.NullPointerException
    at org.adempiere.pos.service.CPOS.getPOSName(CPOS.java:476)
    at org.adempiere.pos.VPOS.dynInit(VPOS.java:309)
    at org.adempiere.pos.VPOS.init(VPOS.java:147)
    at org.compiere.apps.form.FormFrame.openForm(FormFrame.java:360)
    at org.compiere.apps.form.FormFrame.openForm(FormFrame.java:333)
    at org.compiere.apps.AMenuStartItem.startForm(AMenuStartItem.java:352)
    at org.compiere.apps.AMenuStartItem.run(AMenuStartItem.java:184)

**Comment by e-Evolution** [comment]
ec43271

**Comment by e-Evolution** [comment]
Is necessary validate ZK implementation
