### ISSUE TITLE
Error Array index out of range: -1

### ISSUE THREAD

**Issue by e-Evolution** [adempiere/adempierePOS#30]
09:40:05.071   MiniTable.loadTable: Row(array)=0 [111]
09:40:05.397   MiniTable.loadTable: Row(rs)=0 [111]
09:40:05.397   VPOS.init: PosPanel.init - java.awt.Dimension[width=1011,height=804] [111]
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: -1
    at java.util.Vector.removeElementAt(Vector.java:562)
    at javax.swing.table.DefaultTableModel.removeRow(DefaultTableModel.java:462)
    at org.adempiere.pos.POSOrderLinePanel.updateLine(POSOrderLinePanel.java:217)
    at org.adempiere.pos.VPOS.updateLineTable(VPOS.java:493)
    at org.adempiere.pos.POSUpDownPanel.actionPerformed(POSUpDownPanel.java:165)
    at org.compiere.grid.ed.VNumber.fireActionPerformed(VNumber.java:830)
    at org.compiere.grid.ed.VNumber.commitChanges(VNumber.java:694)
    at org.compiere.grid.ed.VNumber.focusLost(VNumber.java:652)
    at java.awt.AWTEventMulticaster.focusLost(AWTEventMulticaster.java:230)
    at java.awt.Component.processFocusEvent(Component.java:6427)
    at java.awt.Component.processEvent(Component.java:6291)
    at java.awt.Container.processEvent(Container.java:2236)
    at java.awt.Component.dispatchEventImpl(Component.java:4891)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
    at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:995)
    at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:661)
    at java.awt.Component.dispatchEventImpl(Component.java:4762)
    at java.awt.Container.dispatchEventImpl(Container.java:2294)
    at java.awt.Component.dispatchEvent(Component.java:4713)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:731)
    at java.awt.EventQueue$4.run(EventQueue.java:729)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
09:41:04.285 MRole.get: AD_Role_ID=102, AD_User_ID=100, reload=false [90]

**Comment by marcalwestf** [comment]
not reproducible as of today.
Closing issue as it is of the beginning of the project.
